"""empty message

Revision ID: 2d6221a53fbe
Revises: None
Create Date: 2015-05-14 11:32:38.733813

"""

# revision identifiers, used by Alembic.
revision = '2d6221a53fbe'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # No-op; example only
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # No-op; example only
    ### end Alembic commands ###
    pass
