"""empty message

Revision ID: 2d6221a53fbe
Revises: None
Create Date: 2015-05-14 11:32:38.733813

"""

# revision identifiers, used by Alembic.
revision = '2d6221a53fbe'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foo', sa.String(), nullable=False),
    sa.Column('bar', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_foo'), 'example', ['foo'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_foo'), table_name='example')
    op.drop_table('example')
    ### end Alembic commands ###
